language: php
php:
  - 5.5
  - 5.4

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y drush
  - curl -sS http://getcomposer.org/installer | php
  - php composer.phar install --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls

notifications:
  slack:
    secure: "Xu9c/a8d98tH0OFuxK/YBR+9lb0Wo8fY/hrDOVb4D6p/lYRaiO6UC2t+FUedoark36zOl9YnWWrt1Ik5mHjlWq2NW0McSeyOvQYmIYA8vx3658uqrvXlgKBpBXXJC3pnj/LGrWSVvdNi9pcCQo3fblc4PLNDlHcQHfaIyVZDfhA="
